### ISSUE TITLE
Plugin does not work on LibreELEC 10 / Kodi 19

### ISSUE THREAD

**Issue by rdorsch** [sarbes/plugin.video.zdftivi#2]
Hi,

I get

2021-03-13 17:21:39.912 T:2488     INFO <general>: initializing python engine.
2021-03-13 17:21:42.538 T:2488     INFO <general>: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.zdf_de_lite/default.py): script successfully run
2021-03-13 17:21:43.092 T:2488     INFO <general>: Python interpreter stopped
2021-03-13 17:21:50.990 T:2513     INFO <general>: initializing python engine.
2021-03-13 17:21:52.843 T:2513     INFO <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.zdf_de_lite/default.py): script successfully run
2021-03-13 17:21:53.265 T:2513     INFO <general>: Python interpreter stopped
2021-03-13 17:22:05.497 T:2547    ERROR <general>: Unable to find plugin 
2021-03-13 17:22:05.497 T:2547    ERROR <general>: GetDirectory - Error getting plugin://
2021-03-13 17:22:05.499 T:970     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://) failed
2021-03-13 17:22:10.394 T:2559     INFO <general>: initializing python engine.
2021-03-13 17:22:10.797 T:2559    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'tivi' object has no attribute 'apiVersion'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.zdftivi/default.py", line 29, in <module>
                                                       o = tivi()
                                                     File "/storage/.kodi/addons/plugin.video.zdftivi/default.py", line 12, in __init__
                                                       libzdf.libzdf.__init__(self)
                                                     File "/storage/.kodi/addons/script.module.libzdf/lib/libzdf.py", line 40, in __init__
                                                       if self.apiVersion == 1:
                                                   AttributeError: 'tivi' object has no attribute 'apiVersion'
                                                   -->End of Python script error report<--
                                                   
2021-03-13 17:22:11.112 T:2559     INFO <general>: Python interpreter stopped
2021-03-13 17:22:11.125 T:2558    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.zdftivi/
2021-03-13 17:22:11.156 T:970     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zdftivi/) failed
2021-03-13 17:22:13.368 T:2564     INFO <general>: initializing python engine.
2021-03-13 17:22:13.735 T:2564    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'tivi' object has no attribute 'apiVersion'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.zdftivi/default.py", line 29, in <module>
                                                       o = tivi()
                                                     File "/storage/.kodi/addons/plugin.video.zdftivi/default.py", line 12, in __init__
                                                       libzdf.libzdf.__init__(self)
                                                     File "/storage/.kodi/addons/script.module.libzdf/lib/libzdf.py", line 40, in __init__
                                                       if self.apiVersion == 1:
                                                   AttributeError: 'tivi' object has no attribute 'apiVersion'
                                                   -->End of Python script error report<--
                                                   
2021-03-13 17:22:14.073 T:2564     INFO <general>: Python interpreter stopped
2021-03-13 17:22:14.076 T:2563    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.zdftivi/
2021-03-13 17:22:14.086 T:970     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zdftivi/) failed

Tested with LibreELEC-iMX6.arm-10.0-nightly-20210312-c5d7822-cubox.img.gz

Any hint or advise would be very welcome, if I just use it incorrectly.

Thanks
Rainer

**Comment by Themanwithoutaplan** [comment]
Just stumbled across in tests for my fork. From the `tokenURL` it looks like the code should be on v2. You can set this manually in the code the tivi class: `self.apiVersion = 2`. This will at least return a result. Going to be a while before I have a fully working update.
